import {writeFile} from 'node:fs/promises';
import {readFile} from '../src/storage.mjs';
const read=async p=>JSON.parse(await readFile(p,'utf8'));
const [old,current,calibration]=await Promise.all([read('data/table-v6.0.json'),read('data/table.json'),read('data/scratch-endurance-calibration.json')]);
const byId=new Map(old.rows.map(r=>[r.id,r])),mean=a=>a.reduce((s,v)=>s+v,0)/Math.max(1,a.length);
function ranks(a){const s=a.map((v,i)=>({v,i})).sort((a,b)=>a.v-b.v),out=[];for(let i=0;i<s.length;){let j=i+1;while(j<s.length&&s[i].v===s[j].v)j++;for(let k=i;k<j;k++)out[s[k].i]=(i+j-1)/2/Math.max(1,s.length-1)*100;i=j;}return out;}
function correlation(a,b){const ma=mean(a),mb=mean(b);return a.reduce((s,x,i)=>s+(x-ma)*(b[i]-mb),0)/Math.sqrt(a.reduce((s,x)=>s+(x-ma)**2,0)*b.reduce((s,x)=>s+(x-mb)**2,0));}
const rows=current.rows.filter(r=>r.level===12&&r.ereter&&byId.get(r.id)?.analysis).map(r=>({id:r.id,title:r.title,difficulty:r.difficulty,bpm:r.bpm,tempo:r.tempo,old:byId.get(r.id).analysis.singleHard5.requiredCapacity,next:r.analysis.singleHard5.requiredCapacity,oldStar:byId.get(r.id).analysis.singleHard5.hardStar,star:r.analysis.singleHard5.hardStar,hc:r.ereter.hcDiff,metrics:r.analysis.metrics,option:r.analysis.singleHard5.recommendation}));
function summarize(group){const a=ranks(group.map(r=>r.old)),b=ranks(group.map(r=>r.next)),e=ranks(group.map(r=>r.hc));return {count:group.length,old:{rho:correlation(a,e),mae:mean(a.map((x,i)=>Math.abs(x-e[i]))),large:a.filter((x,i)=>Math.abs(x-e[i])>=20).length},next:{rho:correlation(b,e),mae:mean(b.map((x,i)=>Math.abs(x-e[i]))),large:b.filter((x,i)=>Math.abs(x-e[i])>=20).length}};}
const a=ranks(rows.map(r=>r.old)),b=ranks(rows.map(r=>r.next)),e=ranks(rows.map(r=>r.hc));rows.forEach((r,i)=>Object.assign(r,{oldRank:a[i],nextRank:b[i],ereterRank:e[i],oldGap:a[i]-e[i],gap:b[i]-e[i]}));
const focus=['_shakunt-A','_syaku_2-A','makin_it-A','dicadica-A','gobblecp-H','dxy-A','titans-X','logic-A','comaaaaa-X'].map(id=>rows.find(r=>r.id===id)).filter(Boolean);
const report={model:current.model,previousModel:old.model,all:summarize(rows),nonSoflan:summarize(rows.filter(r=>!r.tempo?.variable&&!/[～~]/.test(r.bpm))),calibration:{chosen:calibration.chosen,candidate:calibration.candidates[calibration.chosen],holdout:calibration.holdout},tempoCorrections:current.rows.filter(r=>r.bpm!==byId.get(r.id)?.bpm).map(r=>({id:r.id,title:r.title,difficulty:r.difficulty,oldBpm:byId.get(r.id)?.bpm,bpm:r.bpm})),focus,rows};
await writeFile('data/endurance-comparison.json',JSON.stringify(report,null,2));
const n=x=>x.toFixed(2);
const text=`# 連皿の持続負荷と譜面別BPMの修正\n\n${current.model}、比較元${old.model}。H5とereter HCを同じ☆12集合内で百分位化。正の差はモデル側が難しい方向。\n\n## 変更と検証\n\n全${rows.length}譜面の順位相関 ${n(report.all.old.rho)} → ${n(report.all.next.rho)}、平均絶対順位差 ${n(report.all.old.mae)} → ${n(report.all.next.mae)}。20ポイント以上の差 ${report.all.old.large} → ${report.all.next.large}譜面。\n\n譜面別BPMで除外した非ソフラン${report.nonSoflan.count}譜面の相関 ${n(report.nonSoflan.old.rho)} → ${n(report.nonSoflan.next.rho)}、順位差 ${n(report.nonSoflan.old.mae)} → ${n(report.nonSoflan.next.mae)}。以前の「非ソフラン」集計には曲共通BPMによる誤分類があったため、旧集計と母集団が違う。この報告の前後は同じ修正済み母集団。\n\n係数は学習群の誤差だけで選び、保留群は選定後に確認。ereterは過去にも調整に使った母集団であり、独立した実プレイ成功率検証ではない。\n\n- 曲共通BPMでなく、譜面のテンポイベントから範囲とソフラン有無を取得。TITANS RETURN(L)は97～194。ソフラン攻略・HS操作は未対応のまま、比較対象から正しく除外する。\n- 手の動作頻度に含まれる皿の割合を追跡し、鍵盤向けの重複軽減から皿成分を保護する候補を比較。\n- 皿上の移動距離を8秒の減衰履歴に累積し、持続する動作に追加負荷を与える。休憩では回復する。規則的なリズムでも実際の皿移動は消えない。8秒・基準3回/秒・上限などは仮定であり、人間の疲労の実測値ではない。\n- 採用値（保護、持続負荷）: ${JSON.stringify(report.calibration.candidate)}。ソフラン認識やHCN継続判定を再現した修正ではない。\n\n## コメントで確認した難所\n\n- [TITANS RETURN(L)](https://w.atwiki.jp/bemani2dp/pages/3897.html)：低速、HCN絡み、三角同時押しが挙げられている。これを契機に元譜面を確認し、BPM分類の誤りを発見。\n- [灼熱Pt.2(A)](https://w.atwiki.jp/bemani2dp/pages/2797.html)：長い連皿、体力、着地、24分皿への言及がある。短い指疲労だけでは持続負荷を表現できないという仮説を検証した。\n- [GOBBLE(H)](https://w.atwiki.jp/bemani2dp/pages/487.html)：隣接白黒同時押し、付加ノーツ付き縦連、無理皿の取捨、BADハマりが指摘されている。単純に皿枚数を増幅すれば解決する問題とは扱わない。\n\nコメントは個人の攻略経験で、統計的な正解ラベルではない。曲名ごとのミス率補正には使用していない。\n\n## 代表例\n\n| 譜面 | H5☆ 前→後 | H5百分位 前→後 | ereter百分位 | 差 前→後 |\n|---|---:|---:|---:|---:|\n${focus.map(r=>`| ${r.title} ${r.difficulty} | ${r.oldStar.toFixed(1)} → ${r.star.toFixed(1)} | ${n(r.oldRank)} → ${n(r.nextRank)} | ${n(r.ereterRank)} | ${n(r.oldGap)} → ${n(r.gap)} |`).join('\n')}\n\n元データ: data/endurance-comparison.json、候補の検証: data/scratch-endurance-calibration.json。正規配置の特徴値と推奨オプションでのH5は区別する。残る大差は特定の原因が証明されたことを意味しない。\n`;
const limitations=`\n## 改善と残る問題\n\n灼熱2曲の過小評価は縮小した。一方、Makin' Itとdica dicaは過大評価が強まり、全体の改善がすべての皿譜面に当てはまるわけではない。規則的な連皿を省力化する動きと、複雑な皿・着地で持続する負担の区別が次の検証候補になる。これは残差からの仮説で、曲別補正は加えていない。\n\nGOBBLEとLogic Boardの必要能力は今回変わっていない。他曲の順位上昇と☆換算の再校正によって表示値が下がるため、これを配置難の修正と解釈しない。付加ノーツ付き縦連、無理皿の取捨と立て直し、HCN継続判定などは引き続き検証が必要。\n`;
await writeFile('docs/SCRATCH_ENDURANCE.md',text+limitations);console.log(JSON.stringify({...report,rows:undefined,focus:focus.map(r=>({id:r.id,oldGap:r.oldGap,gap:r.gap}))},null,2));
