import {writeFile} from 'node:fs/promises';
import {readFile} from '../src/storage.mjs';
const read=async p=>JSON.parse(await readFile(p,'utf8'));
const [old,current,calibration]=await Promise.all([read('data/table-v5.9.json'),read('data/table.json'),read('data/motor-calibration.json')]);
if(current.model!=='0.6.0-motor-placement-experimental')throw Error('Historical v0.6.0 report; use endurance-report.mjs for the current update');
const byId=new Map(old.rows.map(r=>[r.id,r]));
const mean=a=>a.reduce((s,v)=>s+v,0)/Math.max(1,a.length);
function ranks(a){const s=a.map((v,i)=>({v,i})).sort((a,b)=>a.v-b.v),out=[];for(let i=0;i<s.length;){let j=i+1;while(j<s.length&&s[i].v===s[j].v)j++;for(let k=i;k<j;k++)out[s[k].i]=(i+j-1)/2/Math.max(1,s.length-1)*100;i=j;}return out;}
function correlation(a,b){const ma=mean(a),mb=mean(b);return a.reduce((s,x,i)=>s+(x-ma)*(b[i]-mb),0)/Math.sqrt(a.reduce((s,x)=>s+(x-ma)**2,0)*b.reduce((s,x)=>s+(x-mb)**2,0));}
const rows=current.rows.filter(r=>r.level===12&&r.ereter&&byId.get(r.id)?.analysis).map(r=>({id:r.id,title:r.title,difficulty:r.difficulty,bpm:r.bpm,old:byId.get(r.id).analysis.singleHard5.requiredCapacity,next:r.analysis.singleHard5.requiredCapacity,hc:r.ereter.hcDiff,metrics:r.analysis.metrics,oldMetrics:byId.get(r.id).analysis.metrics,option:r.analysis.singleHard5.recommendation}));
function summarize(group){const a=ranks(group.map(r=>r.old)),b=ranks(group.map(r=>r.next)),e=ranks(group.map(r=>r.hc));return {count:group.length,old:{rho:correlation(a,e),mae:mean(a.map((x,i)=>Math.abs(x-e[i])))},next:{rho:correlation(b,e),mae:mean(b.map((x,i)=>Math.abs(x-e[i])))}};}
const a=ranks(rows.map(r=>r.old)),b=ranks(rows.map(r=>r.next)),e=ranks(rows.map(r=>r.hc));rows.forEach((r,i)=>Object.assign(r,{oldRank:a[i],nextRank:b[i],ereterRank:e[i],oldGap:a[i]-e[i],gap:b[i]-e[i]}));
const groups={};for(const key of ['jackLoad','rapidRunLoad','unilateralBurst','extension','ergonomic','placementTransitionLoad']){const ranked=ranks(rows.map(r=>(key==='placementTransitionLoad'?r.metrics:r.oldMetrics)[key]??0)),group=rows.filter((_,i)=>ranked[i]>=75);groups[key]={n:group.length,oldMeanGap:mean(group.map(r=>r.oldGap)),meanGap:mean(group.map(r=>r.gap))};}
const under=rows.filter(r=>r.oldGap<=-20&&!/[～~]/.test(r.bpm)).sort((a,b)=>a.oldGap-b.oldGap);
const report={model:current.model,previousModel:old.model,all:summarize(rows),nonSoflan:summarize(rows.filter(r=>!/[～~]/.test(r.bpm))),calibration:{chosen:calibration.chosen,candidate:calibration.candidates[calibration.chosen],holdout:calibration.holdout},groups,underestimated:under,rows};
await writeFile('data/motor-comparison.json',JSON.stringify(report,null,2));
const n=x=>x.toFixed(2),fmt=r=>`| ${r.title.replaceAll('|','／')} ${r.difficulty} | ${n(r.oldRank)} → ${n(r.nextRank)} | ${n(r.ereterRank)} | ${n(r.oldGap)} → ${n(r.gap)} | ${r.option} |`;
const text=`# 動作負荷と配置難の再検討\n\nモデル ${current.model}。比較元 ${old.model}。H5とereter HCを同じ☆12集合内で百分位化。正の差はモデル側が難しい方向。\n\n## 検証\n\n全${rows.length}譜面の順位相関 ${n(report.all.old.rho)} → ${n(report.all.next.rho)}、平均絶対順位差 ${n(report.all.old.mae)} → ${n(report.all.next.mae)}。非ソフラン${report.nonSoflan.count}譜面の相関 ${n(report.nonSoflan.old.rho)} → ${n(report.nonSoflan.next.rho)}、平均絶対順位差 ${n(report.nonSoflan.old.mae)} → ${n(report.nonSoflan.next.mae)}。\n\n係数選定は学習群の誤差のみ。曲名で分割した保留群は選定後に確認。過去にもereterで調整した母集団であり、独立した実プレイ検証ではない。CNの架空の再打鍵を除く修正を含むため、全体差は係数変更だけの効果ではない。\n\n## 配置難が低く出た理由\n\n- 手全体の動作頻度、指頻度、片手バースト、高速連続動作が共通する時間制約を重複計上していた。共有分を限定して減らし、縦連の専用負荷・実移動・指の回復時間は保つ。\n- 単独ではホーム運指で取れる鍵でも、複数鍵の形が変わると運指を準備し直す必要がある。混色同時押しへの切り替え、同じ鍵の担当指変更、指の衝突を直前配置と時間間隔から評価する。同形反復とA-B-Aは準備負荷を軽減する。\n- GOBBLEやDXY!などは無理皿を早押し・遅押しへ配分する計画が実戦より有利な可能性もある。この修正だけで全ての過小評価を説明しない。\n- CN/HCN、ソフラン、疲労、実際のRANDOM当たり分布などは別要因。ソフランは係数選定から除外した。BAD後に意図的に一拍休む戦略は未実装。\n\n## 過小評価上位（非ソフラン）\n\n| 譜面 | H5百分位 旧→新 | ereter百分位 | 差 旧→新 | 新推奨 |\n|---|---:|---:|---:|---|\n${under.slice(0,20).map(fmt).join('\n')}\n\n数値は群の傾向と候補原因で、曲別の因果確定や人間のミス率測定ではない。元データは data/motor-comparison.json、係数比較は data/motor-calibration.json。\n`;
const focus=await read('data/motor-focus.json');
const title=id=>current.rows.find(r=>r.id===id)?.title??id;
const counterfactual=`\n## 補正を一つずつ外した比較\n\n新モデルの推奨配置を固定してH5必要能力を再探索。基準はCN修正済みで、旧モデルの最良配置とは異なる場合がある。全8曲で「両方」の値が本番H5と一致することを確認した。\n\n| 譜面 | 基準 | 重複軽減のみ | 配置追加のみ | 両方 |\n|---|---:|---:|---:|---:|\n${focus.map(r=>`| ${title(r.id)} | ${n(r.values.baseline)} | ${n(r.values.reliefOnly)} | ${n(r.values.placementOnly)} | ${n(r.values.combined)} |`).join('\n')}\n\n- **CoMAAAAAAA**：配置切り替えの追加で必要能力が5.21→6.95。両方適用後でも5.96となる。混色同時押しの切り替えを十分に数えていなかったという仮説と整合する。ereterとの差は−52.56→−19.37ポイント。\n- **Logic Board / GOBBLE**：配置追加は難化方向に作用し、全体順位も改善。ただし差は依然−51.15 / −60.46ポイント。直前一動作の準備負荷だけでは足りず、複雑な運指の連続や皿への移行、ずらし入力の成功を過度に楽観している可能性がある。正規の指標だけでは推奨配置での原因を断定できない。\n- **DXY!**：配置追加による難化より共有負荷の軽減が大きく、差は−52.36→−56.75へ悪化。無理皿・連打・鍵盤の組合せと、早押し・遅押し計画の実行失敗は引き続き不足候補。今回の修正で解決したとは扱わない。\n- **TITANS RETURN LEGGENDARIA**：CN拘束の強い譜面で、差は−73.01→−75.71。CN保持指の架空の連打を削除する正当な修正は、欠けているCN/HCN固有の難しさの代替にはならない。拘束中の担当指の維持やHCN継続判定の精査が必要。\n- **灼熱Pt.2**：配置追加が小さい一方、頻度の共有分が大きく減るため、差は−58.77→−74.70へ悪化。今回の軽減は皿の動作頻度にも作用する。複雑な連皿の認識・押し引き失敗を補うモデルは不足しており、総合改善だけを根拠にこの曲の改善とはしない。\n- **エンタンメ～ン / 打打打**：配置追加は小さく、共有負荷の軽減が主に作用。単発5%☆は12.4→11.8 / 12.0→11.5。☆11には今回のereter照合データがないため、改善の実証ではなく変更方向の確認。\n\n## 残る群の偏り\n\n旧版の高速連続動作上位25%の偏りは+9.32→+6.94、片手集中は+7.03→+6.17、縦連は+3.00→+1.42ポイント。新しい配置切り替え負荷上位25%は−7.86→−0.78まで改善した一方、旧版の拡張運指負荷上位25%は−7.56→−8.25で悪化した。配置難のすべてを解消したわけではない。\n`;
await writeFile('docs/MOTOR_PLACEMENT.md',text+counterfactual);console.log(JSON.stringify({...report,rows:undefined,underestimated:under.slice(0,6).map(r=>({id:r.id,oldGap:r.oldGap,gap:r.gap}))},null,2));
